name = "workers"
description = "Simple task pool for parallelization"
version = "0.1.0"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0"
website = ""
tags = ["tasking", "parallelization", "pool"]
